version: "3.9"
services:
  account:
    build: ./src/account-service/.
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: password
      PORT: 8080
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db: